# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build app
        shell: cmd
        run: cl /EHsc src/main.c src/stack.c /link /out:stack.exe
        
      - name: create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: stack.exe
          retention-days: 1

  notification:
    runs-on: ubuntu-latest
    steps:
      - name: send to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_DEBUG }}
          token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
          args: The ${{ github.event_name }} event triggered first step.
          message: Egor Trukhin
          document: stack.exe
          
